from typing import Any, Iterator, List, Optional, Union

from requests import Response


class V4LiveResponse:
    @property
    def data(self) -> dict: ...
    @property
    def request_kwargs(self) -> dict: ...
    @property
    def response(self) -> Response: ...
    @property
    def status_code(self) -> int: ...
    def __getitem__(self, item) -> Union[dict, list]: ...
    def __iter__(self) -> Iterator: ...
    def extract(self) -> Any: ...
    def items(self) -> Iterator: ...
    def pages(self) -> Iterator: ...
    def iter_items(self) -> Iterator: ...


class V4LiveExecutorResponse:
    def __call__(self) -> V4LiveResponse: ...
    @property
    def data(self) -> dict: ...
    @property
    def status_code(self) -> int: ...


class V4LiveExecutor:
    def post(
        self,
        *,
        data: dict = ...,
        params: Optional[dict] = ...,
        headers: Optional[dict] = ...,
    ) -> V4LiveExecutorResponse: ...
    def help(self) -> "V4LiveExecutor": ...


class YandexDirectV4Live:
    def __init__(
        self,
        *,
        access_token: str,
        login: Optional[str] = None,
        is_sandbox: bool = False,
        language: str = "en",
        retry_if_exceeded_limit: bool = True,
        retries_if_server_error: int = 5,
    ) -> None: ...

    def v4live(self) -> V4LiveExecutor: ...
